#include <gtest/gtest.h>
#include "ShipStabilityLib/Version.h"  // Generated by CMake
#include <iostream>

int main(int argc, char **argv) {
    std::cout << "=== ShipStabilityLib Test Suite ===\n";
    std::cout << "Library version: " << SHIPSTABILITYLIB_VERSION
              << " ("
              << SHIPSTABILITYLIB_VERSION_MAJOR << "."
              << SHIPSTABILITYLIB_VERSION_MINOR << "."
              << SHIPSTABILITYLIB_VERSION_PATCH << ")\n";
    std::cout << "===================================\n\n";

    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
